# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'socket_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.l_host = QtWidgets.QLabel(self.centralwidget)
        self.l_host.setObjectName("l_host")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_host)
        self.input_host = QtWidgets.QLineEdit(self.centralwidget)
        self.input_host.setText("")
        self.input_host.setObjectName("input_host")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_host)
        self.l_port = QtWidgets.QLabel(self.centralwidget)
        self.l_port.setObjectName("l_port")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_port)
        self.input_port = QtWidgets.QLineEdit(self.centralwidget)
        self.input_port.setText("")
        self.input_port.setObjectName("input_port")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_port)
        self.l_conn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.l_conn.setFont(font)
        self.l_conn.setObjectName("l_conn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l_conn)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_status)
        self.l_type = QtWidgets.QLabel(self.centralwidget)
        self.l_type.setObjectName("l_type")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.l_type)
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        self.label_type.setObjectName("label_type")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_type)
        self.verticalLayout.addLayout(self.formLayout)
        self.conn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.conn_btn.setObjectName("conn_btn")
        self.verticalLayout.addWidget(self.conn_btn)
        self.msg_all = QtWidgets.QTextEdit(self.centralwidget)
        self.msg_all.setObjectName("msg_all")
        self.verticalLayout.addWidget(self.msg_all)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.input_msg = QtWidgets.QLineEdit(self.centralwidget)
        self.input_msg.setObjectName("input_msg")
        self.horizontalLayout_2.addWidget(self.input_msg)
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_2.addWidget(self.send_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuhttp = QtWidgets.QMenu(self.menubar)
        self.menuhttp.setObjectName("menuhttp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionserver = QtWidgets.QAction(MainWindow)
        self.actionserver.setCheckable(True)
        self.actionserver.setChecked(True)
        self.actionserver.setObjectName("actionserver")
        self.actionclient = QtWidgets.QAction(MainWindow)
        self.actionclient.setObjectName("actionclient")
        self.actionarp = QtWidgets.QAction(MainWindow)
        self.actionarp.setObjectName("actionarp")
        self.actionip = QtWidgets.QAction(MainWindow)
        self.actionip.setObjectName("actionip")
        self.actionhttp = QtWidgets.QAction(MainWindow)
        self.actionhttp.setObjectName("actionhttp")
        self.menu.addAction(self.actionserver)
        self.menu.addAction(self.actionclient)
        self.menuhttp.addAction(self.actionarp)
        self.menuhttp.addAction(self.actionip)
        self.menuhttp.addAction(self.actionhttp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuhttp.menuAction())

        self.retranslateUi(MainWindow)
        self.conn_btn.clicked.connect(self.slot_conn)
        # self.send_btn.clicked.connect(MainWindow.slot_send)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SS[Sunday_Study] Networking Tool"))
        self.l_host.setText(_translate("MainWindow", "Host"))
        self.input_host.setPlaceholderText(_translate("MainWindow", "ex) 127.0.0.1 or domain"))
        self.l_port.setText(_translate("MainWindow", "Port"))
        self.input_port.setPlaceholderText(_translate("MainWindow", "ex) 8080 / default 4444"))
        self.l_conn.setText(_translate("MainWindow", "Status"))
        self.label_status.setText(_translate("MainWindow", "Disconnection"))
        self.l_type.setText(_translate("MainWindow", "Type"))
        self.label_type.setText(_translate("MainWindow", "Server"))
        self.conn_btn.setText(_translate("MainWindow", "Start Connecting"))
        self.label_4.setText(_translate("MainWindow", "msg"))
        self.send_btn.setText(_translate("MainWindow", "Send"))
        self.menu.setTitle(_translate("MainWindow", "socket"))
        self.menuhttp.setTitle(_translate("MainWindow", "send packet"))
        self.actionserver.setText(_translate("MainWindow", "server side"))
        self.actionclient.setText(_translate("MainWindow", "Client side"))
        self.actionarp.setText(_translate("MainWindow", "arp"))
        self.actionip.setText(_translate("MainWindow", "ip"))
        self.actionhttp.setText(_translate("MainWindow", "http"))


    def slot_conn(self):

        self.conn_btn.setText("Connectied")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

