# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'socket_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lab_conn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lab_conn.setFont(font)
        self.lab_conn.setObjectName("lab_conn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lab_conn)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_2.addWidget(self.send_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.lineEdit_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuhttp = QtWidgets.QMenu(self.menubar)
        self.menuhttp.setObjectName("menuhttp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionserver = QtWidgets.QAction(MainWindow)
        self.actionserver.setCheckable(True)
        self.actionserver.setChecked(True)
        self.actionserver.setObjectName("actionserver")
        self.actionclient = QtWidgets.QAction(MainWindow)
        self.actionclient.setObjectName("actionclient")
        self.actionarp = QtWidgets.QAction(MainWindow)
        self.actionarp.setObjectName("actionarp")
        self.actionip = QtWidgets.QAction(MainWindow)
        self.actionip.setObjectName("actionip")
        self.actionhttp = QtWidgets.QAction(MainWindow)
        self.actionhttp.setObjectName("actionhttp")
        self.menu.addAction(self.actionserver)
        self.menu.addAction(self.actionclient)
        self.menuhttp.addAction(self.actionarp)
        self.menuhttp.addAction(self.actionip)
        self.menuhttp.addAction(self.actionhttp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuhttp.menuAction())
        self.label_6.setBuddy(self.textEdit)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked['bool'].connect(self.label_3.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SS[Sunday_Study] Networking Tool"))
        self.label.setText(_translate("MainWindow", "IP Address"))
        self.lineEdit_2.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "PORT"))
        self.lineEdit.setText(_translate("MainWindow", "12345"))
        self.lab_conn.setText(_translate("MainWindow", "STATUS"))
        self.label_3.setText(_translate("MainWindow", "connection/disconnection"))
        self.label_5.setText(_translate("MainWindow", "Type"))
        self.label_6.setText(_translate("MainWindow", "Client"))
        self.pushButton.setText(_translate("MainWindow", "connection/disconnection"))
        self.label_4.setText(_translate("MainWindow", "msg"))
        self.send_btn.setText(_translate("MainWindow", "Send"))
        self.menu.setTitle(_translate("MainWindow", "socket"))
        self.menuhttp.setTitle(_translate("MainWindow", "send packet"))
        self.actionserver.setText(_translate("MainWindow", "server"))
        self.actionclient.setText(_translate("MainWindow", "client"))
        self.actionarp.setText(_translate("MainWindow", "arp"))
        self.actionip.setText(_translate("MainWindow", "ip"))
        self.actionhttp.setText(_translate("MainWindow", "http"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

